#spring:
#  application:
#    name: patient-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/authServiceDb
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  jwt:
#    secret: ${JWT_SECRET}

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
server:
  port: 8081
