### GET request to update patient
PUT http://localhost:8080/patients/ffc0a76a-0a12-4c18-aa58-5302c4e77f7f
Content-Type: application/json

{
  "name": "douglas updated",
  "email": "douglas400@gmail.com",
  "address": "123 main street",
  "getDateOfBirth": "1999-01-01"
}

###