version: '3.8'

services:
  auth_service_db:
    image: postgres:latest
    container_name: auth_service_DB
    environment:
      POSTGRES_DB: authServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /media/modestnerds/Doug/docker-volumes/auth_service_db:/var/lib/postgres
    networks:
      - internal-network

  auth_service:
    build: .
    image: auth_service_img
    container_name: auth_service
    volumes:
      - /media/modestnerds/Doug/docker-volumes/patient-service:/var/lib/auth_service
    environment:
      DATABASE_URL: jdbc:postgresql://auth_service_db:5432/authServiceDb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      JWT_SECRET: myveryprivate64bitsecretmyveryprivate64bitsecretmyveryprivate64bitsecret
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge