version: '3.8'

services:
  auth_service_db:
    image: postgres:latest
    container_name: auth_service_DB
    environment:
      POSTGRES_DB: authServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  auth_service:
    build: .
    image: auth_service_img
    container_name: auth_service
    environment:
      DATABASE_URL: jdbc:postgresql://auth_service_db:5432/authServiceDb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      JWT_SECRET: myveryprivate64bitsecretmyveryprivate64bitsecretmyveryprivate64bitsecret
    ports:
      - "8081:8081"
    depends_on:
      - auth_service_db
