version: '3.8'

services:
  patient-service-db:
    image: mysql:latest
    container_name: patient-service-db
    environment:
      MYSQL_DATABASE: patientserviceDB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /media/modestnerds/Doug/docker-volumes/patient-service-db:/var/lib/mysql
    networks:
      - internal-network



  patient-service-app:
    image: patient-service-app
    container_name: patient-service-app
    environment:
      DATABASE_URL: jdbc:mysql://patient-service-db:3306/patientserviceDB
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    ports:
      - "8082:8082"  # Expose the Spring Boot application port
      - "9090:9090"  # Expose the gRPC port
    volumes:
      - /media/modestnerds/Doug/docker-volumes/patient-service:/var/lib/patient-service
    depends_on:
      - patient-service-db  # Ensure the database starts first
    networks:
      - internal-network

  billing-service:
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "8083:8083"
      - "9001:9001"  # This exposes the gRPC port
    volumes:
      - /media/modestnerds/Doug/docker-volumes/billing-service:/var/lib/billing-service  # Updated path

    networks:
      - internal-network



  kafka:
    image: 'bitnami/kafka:4.0.0'
    container_name: kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    volumes:
      - /media/modestnerds/Doug/docker-volumes/patient-service:/var/lib/kafka

    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,EXTERNAL://host.docker.internal:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - BITNAMI_DEBUG=yes

    networks:
      - internal-network


networks:
  internal-network:
    driver: bridge