#version: '3.8'
#
#services:
#  spring-boot-app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: patient-service-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patientserviceDB
#      SPRING_DATASOURCE_USERNAME: admin_user
#      SPRING_DATASOURCE_PASSWORD: password
#    networks:
#      - internal
#
#networks:
#  internal:
#    external: true
