spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patientserviceDB
    username: admin_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 4000

grpc:
  client:
    billing-service:
      address: static://localhost:9001
