spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patientserviceDB
    username: admin_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

billing:
  service:
    address: localhost  # gRPC server address
    grpc:
      port: 9001  # gRPC server port
