version: '3.8'

services:
  billing-service:
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "8080:8080"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:



